export const ru = {
  "meta.title": "Meta · Facebook Ads",
  "meta.schedule": "Автообновление каждый день в 08:00",
  "meta.settings": "Настроить Meta API",
  "meta.api": "Meta API",
  "meta.accountId": "Account ID",
  "meta.token": "Токен доступа",
  "meta.connect": "Подключить",
  "meta.disconnect": "Отключить",
  "meta.refresh": "Обновить",
  "meta.saving": "Проверяем подключение…",
  "meta.lastSuccess": "Последнее обновление:",
  "meta.help": "Account ID можно вставить с act_ или без него. Токен сохраняется на сервере в зашифрованном виде. Загружаются кампании, объявления и статистика за последние 30 полных дней. Валюта аккаунта должна совпадать с валютой проекта. Отключение сохраняет загруженные данные.",
  "meta.status.QUEUED": "В очереди",
  "meta.status.RUNNING": "Загружаем данные…",
  "meta.status.SUCCESS": "Данные обновлены",
  "meta.status.ERROR": "Ошибка обновления",
  "meta.status.AUTH_REQUIRED": "Нужен новый токен",
  "meta.error.token": "Токен недействителен или истёк. Вставьте новый токен.",
  "meta.error.currency": "Валюта рекламного аккаунта не совпадает с валютой проекта. Измените валюту проекта и повторите подключение.",
  "meta.error.configuration": "На сервере не настроен ключ шифрования интеграций. Обратитесь к администратору.",
  "meta.error.conflict": "Не удалось связать кампании с проектом: конфликт данных интеграции.",
  "meta.error.provider": "Не удалось загрузить данные из Meta. Проверьте Account ID, доступ токена и повторите попытку.",
  "meta.error.read": "Не удалось загрузить настройки интеграции.",
  "brand.title": "AdPulse",
  "nav.dashboard": "Дашборд", "nav.projects": "Проекты", "nav.tasks": "Задачи",
  "nav.crm": "CRM", "nav.reports": "Отчёты", "nav.archive": "Архив", "nav.sections": "Разделы",
  "nav.collapse": "Свернуть меню", "nav.expand": "Развернуть меню",
  "module.soon.title": "Модуль в разработке", "module.soon.description": "Этот раздел ещё не реализован.",
  "projects.unselected.title": "Проект не выбран",
  "projects.unselected.description": "Выберите из списка или создайте новый",
  "clients.section": "Клиенты", "clients.new": "Новый клиент",
  "clients.empty.title": "Выберите клиента", "clients.empty.description": "Или добавьте нового клиента в боковой панели",
  "clients.notFound.title": "Клиент не найден", "clients.notFound.description": "Возможно, он был удалён",
  "client.edit": "Редактировать", "client.delete": "Удалить", "client.delete.title": "Удалить клиента?", "client.delete.body": "Клиент, все его кампании и лиды его воронки будут удалены безвозвратно.",
  "campaigns.title": "Кампании", "campaigns.one": "Кампания",
  "campaigns.empty.title": "Кампаний пока нет",
  "campaigns.loading": "Загрузка кампаний",
  "campaigns.empty.description": "Кампании появятся, когда будут подключены рекламные кабинеты",
  "metric.spend": "Расход", "metric.impressions": "Показы", "metric.reach": "Охват",
  "metric.clicks": "Клики", "metric.conversions": "Конверсии",
  "metric.ctr": "CTR", "metric.cpc": "CPC", "metric.cpm": "CPM", "metric.cpa": "CPA",
  "metric.roas": "ROAS", "metric.frequency": "Частота", "metric.total": "Итого",
  "channel.META": "Meta", "channel.GOOGLE": "Google Ads", "channel.YANDEX": "Яндекс Директ",
  "channel.VK": "VK Реклама", "channel.TIKTOK": "TikTok", "channel.LINKEDIN": "LinkedIn",
  "channel.TELEGRAM": "Telegram Ads",
  "status.ACTIVE": "Активна", "status.LEARNING": "Обучение", "status.PAUSED": "Пауза",
  "status.REJECTED": "Отклонена", "status.ENDED": "Завершена",
  "registration.title": "Регистрация", "stepper.step": "Шаг",
  "registration.employee.title": "Регистрация сотрудника",
  "registration.client.title": "Регистрация клиента",
  "registration.join.title": "Присоединиться к компании",
  "registration.invalid.title": "Ссылка недействительна",
  "registration.invalid.description": "Приглашение не найдено, уже использовано или отозвано. Попросите новое.",
  "registration.password.confirm": "Повторите пароль",
  "registration.password.mismatch": "Пароли не совпадают",
  "registration.password.required": "Введите пароль",
  "registration.password.confirmRequired": "Повторите пароль ещё раз",
  "registration.organization.required": "Введите название организации",
  "registration.avatar.create": "Создать аватар",
  "registration.avatar.upload": "Загрузить изображение",
  "registration.avatar.wrongType": "Нужно изображение",
  "registration.submit": "Зарегистрироваться",
  "registration.next": "Далее", "registration.back": "Назад",
  "registration.project.name": "Название проекта",
  "period.label": "Период",
  "period.7d": "7 дней", "period.month": "Этот месяц", "period.prevMonth": "Прошлый месяц",
  "period.from": "От", "period.to": "До",
  "period.from.open": "Открыть календарь даты начала", "period.to.open": "Открыть календарь даты окончания",
  "period.from.dialog": "Выберите дату начала", "period.to.dialog": "Выберите дату окончания",
  "period.previousMonth": "Предыдущий месяц", "period.nextMonth": "Следующий месяц",
  "period.invalid": "Введите дату в формате ГГГГ-ММ-ДД",
  "period.reversed": "Дата «От» не может быть позже даты «До»",
  "summary.title": "Показатели за период",
  "chart.title": "Динамика по дням", "chart.peak": "Максимум за день",
  "chart.empty": "За период нет данных",
  "creatives.dialog": "Креатив объявления",
  "creatives.previous": "Предыдущее объявление", "creatives.next": "Следующее объявление",
  "creatives.empty": "У объявления нет креатива",
  "creatives.failed": "Не удалось загрузить креатив",
  "creatives.external": "Смотреть в Ads Manager",
  "adSets.title": "Группы объявлений", "adSets.one": "Группа",
  "adSets.empty": "Групп объявлений пока нет",
  "campaign.notFound.title": "Кампания не найдена", "campaign.back": "Назад к кампаниям",
  "dashboard.project": "Проект", "dashboard.sources": "Источники",
  "dashboard.sources.empty": "Пока нет данных по источникам",
  "dashboard.sources.campaigns": "Кампаний", "dashboard.spendByDay": "Расход по дням",
  "projects.new": "Новый проект", "projects.empty.title": "Проектов пока нет",
  "projects.priorityFilter": "Фильтр по приоритету", "projects.allPriorities": "Все приоритеты",
  "projects.pinned": "Закреплённые", "projects.pin": "Закрепить", "projects.unpin": "Открепить",
  "projects.order.failed": "Не удалось сохранить порядок списка",
  "projects.group.new": "Создать группу", "projects.group.dialog": "Новая группа",
  "projects.group.name": "Название группы", "projects.group.required": "Введите название группы",
  "projects.group.delete": "Удалить группу",
  "projects.group.notEmpty": "Сначала уберите из группы все проекты",
  "projects.empty.description": "Создайте первый проект и привяжите к нему клиента",
  "project.form.new.title": "Новый проект", "project.form.edit.title": "Редактирование проекта",
  "project.name.label": "Название проекта", "project.name.required": "Введите название проекта",
  "project.niche.label": "Ниша", "project.budget.label": "Бюджет / мес.", "project.currency.label": "Валюта",
  "project.client.label": "Клиент", "project.client.required": "Выберите клиента",
  "project.client.empty": "Сначала заведите клиента в контактной книге",
  "project.logo.label": "Логотип или картинка", "project.logo.pick": "Выбрать файл",
  "project.logo.failed": "Не удалось сохранить изображение",
  "priority.title": "Приоритет",
  "priority.CRITICAL": "Очень важно", "priority.URGENT": "Есть срочные задачи",
  "priority.WAITING": "В работе, ждём результата", "priority.IDLE": "Нет задач",
  "priority.NEW": "Новый",
  "project.edit": "Редактировать", "project.delete": "Удалить",
  "project.delete.title": "Удалить проект?",
  "project.delete.body": "Проект и все его листы будут удалены безвозвратно.",
  "project.notFound.title": "Проект не найден",
  "form.new.title": "Новый клиент", "form.edit.title": "Редактирование клиента", "form.name.label": "Имя", "form.niche.label": "Ниша", "form.budget.label": "Бюджет $/мес.",
  "form.email.label": "Email клиента", "form.email.invalid": "Введите корректный email",
  "action.cancel": "Отмена", "action.copied": "Скопировано", "action.create": "Создать", "action.save": "Сохранить", "action.delete": "Удалить", "action.close": "Закрыть", "action.add": "Добавить",
  "state.error.title": "Что-то пошло не так", "state.loading": "Загрузка…", "state.retry": "Повторить", "alert.dismiss": "Закрыть уведомление", "alert.region": "Уведомления",
  "auth.login.title": "Вход", "auth.name.label": "Имя", "auth.email.label": "Email", "auth.password.label": "Пароль",
  "auth.login.submit": "Войти", "auth.logout": "Выйти",
  "account.settings": "Настройки", "profile.title": "Настройки профиля", "profile.currentPassword": "Текущий пароль", "profile.newPassword": "Новый пароль",
  "profile.passwordHint": "Оставьте оба поля пароля пустыми, чтобы не менять его.", "profile.avatar": "Аватар", "profile.regenerate": "Изменить аватар", "profile.saved": "Профиль сохранён",
  "profile.loadFailed": "Не удалось загрузить профиль", "profile.saveFailed": "Не удалось сохранить профиль",
  "avatar.title": "Редактор аватара", "avatar.random": "Случайный вариант", "avatar.save": "Сохранить аватар",
  "company.team": "Сотрудники компании", "company.team.empty": "Пока никого нет",
  "employee.access": "Доступ к проектам", "employee.access.add": "Добавить проект",
  "employee.access.remove": "Убрать",
  "employee.access.remove.title": "Убрать доступ к проекту?",
  "employee.access.remove.body": "Сотрудник перестанет видеть проект",
  "employee.access.remove.confirm": "Убрать проект", "employee.access.none": "Проекты не назначены",
  "employee.access.wholeClient": "все проекты клиента",
  "contacts.people": "Люди клиента", "contacts.people.empty": "У этого клиента пока нет людей",
  "contacts.people.invite": "Пригласить в компанию",
  "contacts.title": "Контактная книга", "contacts.empty": "Клиентов пока нет", "contacts.choose": "Выберите клиента слева",
  "contacts.fullName": "Полное имя", "contacts.organization": "Название организации", "contacts.unp": "УНП",
  "contacts.phone": "Телефон", "contacts.telegram": "Телеграм", "contacts.email": "Почта", "contacts.website": "Сайт",
  "contacts.avatar.change": "Изменить изображение", "contacts.avatar.upload": "Загрузить лого",
  "contacts.avatar.generate": "Создать аватар", "contacts.avatar.failed": "Не удалось сохранить изображение",
  "contacts.edit": "Редактировать контакт", "contacts.new": "Новый контакт", "contacts.name": "Клиент", "contacts.name.required": "Введите имя",
  "theme.toDark": "Включить тёмную тему", "theme.toLight": "Включить светлую тему", "team.role": "Роль",
  "role.ADMIN": "Администратор", "role.MANAGER": "Менеджер", "role.GUEST": "Гость", "role.CLIENT": "Сотрудник клиента", "role.CLIENT_ADMIN": "Главный у клиента",
  "invites.title": "Приглашения", "invites.role": "Роль приглашения", "invites.create": "Создать приглашение",
  "invites.copy": "Скопировать код", "invites.revoke": "Отозвать", "invites.empty": "Нет активных приглашений",
  "invites.loadFailed": "Не удалось загрузить приглашения",
  "invites.link": "Ссылка для регистрации", "invites.copyLink": "Скопировать ссылку",
  "invites.copied": "Ссылка скопирована",
  "invites.projects": "Проекты", "invites.projects.required": "Выберите хотя бы один проект",
  "invites.createClient": "Пригласить клиента", "invites.createEmployee": "Пригласить сотрудника",
  "invites.failed": "Не удалось создать приглашение",
  "invites.submit": "Создать приглашение",
  "invites.done": "Готово", "invites.ready": "Приглашение создано",
  "invites.clientHint": "Клиент заполнит свои данные сам при регистрации.",
  "contacts.directory.clients": "Клиенты", "contacts.directory.employees": "Сотрудники",
  "contacts.directory.label": "Кого показывать",
  "contacts.employees.empty": "Сотрудников пока нет",
  "activity.title": "История действий", "activity.empty": "Действий пока нет",
  "activity.loadFailed": "Не удалось загрузить историю", "activity.more": "Показать ещё",
  "activity.action.CREATE": "Создание", "activity.action.UPDATE": "Изменение", "activity.action.DELETE": "Удаление",
  "validation.required": "Обязательное поле", "validation.invalid": "Проверьте значение",
  "presence.title": "Сейчас в системе",
  "crm.title": "CRM", "crm.board": "Воронка", "crm.boardUnavailable": "Воронка недоступна",
  "crm.empty": "Нет лидов", "crm.loadFailed": "Не удалось загрузить лиды",
  "crm.create": "Добавить лид", "crm.open": "Открыть лид", "crm.drag": "Перетащить лид",
  "crm.stage.NEW": "Новый лид", "crm.stage.CONTACTED": "Связались",
  "crm.stage.QUALIFIED": "Квалифицирован", "crm.stage.PROPOSAL": "Предложение",
  "crm.stage.NEGOTIATION": "Переговоры", "crm.stage.WON": "Выигран",
  "crm.stage.LOST": "Проигран", "crm.stage.DEFERRED": "Отложен",
  "crm.form.name": "Имя / название", "crm.form.project": "Проект", "crm.form.campaign": "Кампания",
  "crm.form.noProject": "Не указан", "crm.form.noCampaign": "Не указана", "crm.form.company": "Компания",
  "crm.form.phone": "Телефон", "crm.form.email": "Email",
  "crm.form.website": "Сайт", "crm.form.source": "Источник", "crm.form.notes": "Заметки",
  "crm.form.stage": "Этап", "crm.form.nameRequired": "Введите имя",
  "crm.form.create": "Создать", "crm.form.save": "Сохранить", "crm.form.edit": "Лид",
  "crm.form.saveFailed": "Не удалось сохранить лид",
  "crm.noSource": "Не указан",
  "crm.delete": "Удалить", "crm.deleteConfirm": "Удалить лид",
  "crm.deleteQuestion": "Удалить лид безвозвратно?",
  "crm.moveFailed": "Не удалось переместить лид",
  "tasks.title": "Задачи", "tasks.create": "Новая задача", "tasks.empty": "Задач пока нет",
  "tasks.loadFailed": "Не удалось загрузить задачи", "tasks.moveFailed": "Не удалось переместить задачу",
  "tasks.saveFailed": "Не удалось сохранить задачу",
  "tasks.column.IDEA": "Идея", "tasks.column.ARCHIVED": "Архив", "tasks.column.IN_PROGRESS": "В работе",
  "tasks.column.NEEDS_FIX": "На исправление", "tasks.column.IN_REVIEW": "На проверке", "tasks.column.DONE": "Готово",
  "tasks.priority.LOW": "Низкий", "tasks.priority.MEDIUM": "Средний",
  "tasks.priority.HIGH": "Высокий", "tasks.priority.URGENT": "Срочный",
  "tasks.form.title": "Название", "tasks.form.description": "Описание",
  "tasks.form.project": "Проект", "tasks.form.campaign": "Кампания", "tasks.form.visibleToClient": "Видно клиенту", "tasks.form.column": "Этап",
  "tasks.noDescription": "Без описания",
  "tasks.inFlight.title": "Задачи в работе", "tasks.inFlight.empty": "Нет задач в работе",
  "tasks.ofCampaign.title": "Задачи кампании", "tasks.ofCampaign.empty": "К этой кампании нет задач", "tasks.form.wholeProject": "Общий", "tasks.form.assignee": "Ответственный",
  "tasks.form.priority": "Приоритет", "tasks.form.unassigned": "Не назначен",
  "tasks.form.projectUnchosen": "Не выбран",
  "tasks.editor.attachment": "Вложение",
  "tasks.attachments.remove": "Удалить вложение",
  "tasks.attachments.removeFailed": "Не удалось удалить вложение",
  "tasks.form.create": "Создать задачу", "tasks.form.save": "Сохранить",
  "tasks.form.titleRequired": "Введите название", "tasks.form.projectRequired": "Выберите проект",
  "tasks.edit": "Редактировать", "tasks.delete": "Удалить",
  "tasks.delete.title": "Удалить задачу?",
  "tasks.delete.description": "Задача и её вложения будут удалены безвозвратно.",
  "tasks.delete.confirm": "Удалить задачу",
  "tasks.editor.placeholder": "Опишите задачу. Картинку можно вставить через Ctrl+V или перетащить сюда.",
  "tasks.editor.uploading": "Загрузка изображения…",
  "tasks.editor.uploadFailed": "Не удалось загрузить изображение",
  "tasks.editor.tooLarge": "Изображение слишком большое, максимум 10 МБ",
  "tasks.editor.wrongType": "Можно загружать только PNG, JPEG, WebP и GIF",
  "tasks.drag": "Перетащить задачу", "tasks.open": "Открыть задачу",
  "tasks.attachments": "Вложения", "tasks.attachments.empty": "Файлов нет",
  "tasks.attachments.count": "Вложений", "tasks.noProject": "Без проекта",
  "auth.email.invalid": "Введите корректный email", "auth.password.tooShort": "Минимум 8 символов", "auth.name.required": "Введите имя",
} as const;
export type MessageKey = keyof typeof ru;
export function t(key: MessageKey): string {
  return ru[key];
}
