export const ru = {
  "brand.title": "AdPulse",
  "nav.dashboard": "Дашборд", "nav.projects": "Проекты", "nav.tasks": "Задачи",
  "nav.reports": "Отчёты", "nav.archive": "Архив", "nav.sections": "Разделы",
  "nav.collapse": "Свернуть меню", "nav.expand": "Развернуть меню",
  "module.soon.title": "Модуль в разработке", "module.soon.description": "Этот раздел ещё не реализован.",
  "projects.pick": "Выберите проект слева",
  "clients.section": "Клиенты", "clients.new": "Новый клиент",
  "clients.empty.title": "Выберите клиента", "clients.empty.description": "Или добавьте нового клиента в боковой панели",
  "clients.notFound.title": "Клиент не найден", "clients.notFound.description": "Возможно, он был удалён",
  "client.edit": "Редактировать", "client.delete": "Удалить", "client.delete.title": "Удалить клиента?", "client.delete.body": "Клиент и все его кампании будут удалены безвозвратно.",
  "sheet.date": "ДАТА", "sheet.total": "ИТОГО", "sheet.title": "Статистика по дням", "sheet.addDay": "Добавить день", "sheet.value.invalid": "Введите число",
  "sheet.date.choose": "Выберите дату", "sheet.date.previousMonth": "Предыдущий месяц", "sheet.date.nextMonth": "Следующий месяц", "sheet.date.failed": "Не удалось перенести день",
  "sheet.delete": "Удалить день", "sheet.delete.title": "Удалить день?", "sheet.delete.body": "День и все его значения будут удалены безвозвратно.",
  "campaigns.empty.title": "Листов пока нет", "campaigns.empty.description": "У этого клиента ещё нет кампаний", "campaigns.new": "Новый лист",
  "campaigns.rename": "Переименовать лист", "campaigns.delete": "Удалить лист", "campaigns.delete.title": "Удалить лист?", "campaigns.delete.body": "Лист и все его дни будут удалены безвозвратно.",
  "campaigns.form.new.title": "Новый лист", "campaigns.form.edit.title": "Переименовать лист", "campaigns.empty.action": "Создать лист", "campaigns.form.name.required": "Введите название",
  "projects.new": "Новый проект", "projects.empty.title": "Проектов пока нет",
  "projects.empty.description": "Создайте первый проект и привяжите к нему клиента",
  "project.form.new.title": "Новый проект", "project.form.edit.title": "Редактирование проекта",
  "project.name.label": "Название проекта", "project.name.required": "Введите название проекта",
  "project.niche.label": "Ниша", "project.budget.label": "Бюджет / мес.",
  "project.client.label": "Клиент", "project.client.required": "Выберите клиента",
  "project.client.empty": "Сначала заведите клиента в контактной книге",
  "project.logo.label": "Логотип или картинка", "project.logo.pick": "Выбрать файл",
  "project.logo.failed": "Не удалось сохранить изображение",
  "priority.title": "Приоритет",
  "priority.CRITICAL": "Очень важно", "priority.URGENT": "Есть срочные задачи",
  "priority.WAITING": "В работе, ждём результата", "priority.IDLE": "Нет задач",
  "priority.NEW": "Новый",
  "project.edit": "Редактировать", "project.delete": "Удалить",
  "project.delete.title": "Удалить проект?",
  "project.delete.body": "Проект и все его листы будут удалены безвозвратно.",
  "project.notFound.title": "Проект не найден",
  "form.new.title": "Новый клиент", "form.edit.title": "Редактирование клиента", "form.name.label": "Имя", "form.niche.label": "Ниша", "form.budget.label": "Бюджет $/мес.",
  "form.email.label": "Email клиента", "form.email.invalid": "Введите корректный email",
  "action.cancel": "Отмена", "action.create": "Создать", "action.save": "Сохранить", "action.delete": "Удалить", "action.close": "Закрыть",
  "state.error.title": "Что-то пошло не так", "state.loading": "Загрузка…", "state.retry": "Повторить",
  "auth.login.title": "Вход", "auth.signup.title": "Создание аккаунта", "auth.name.label": "Имя", "auth.email.label": "Email", "auth.password.label": "Пароль", "auth.inviteCode.label": "Код приглашения",
  "auth.login.submit": "Войти", "auth.signup.submit": "Создать аккаунт", "auth.login.link": "Уже есть аккаунт? Войти", "auth.signup.link": "Нет аккаунта? Зарегистрироваться", "auth.logout": "Выйти",
  "account.settings": "Настройки", "profile.title": "Настройки профиля", "profile.currentPassword": "Текущий пароль", "profile.newPassword": "Новый пароль",
  "profile.passwordHint": "Оставьте оба поля пароля пустыми, чтобы не менять его.", "profile.avatar": "Аватар", "profile.regenerate": "Изменить аватар", "profile.saved": "Профиль сохранён",
  "profile.loadFailed": "Не удалось загрузить профиль", "profile.saveFailed": "Не удалось сохранить профиль",
  "avatar.title": "Редактор аватара", "avatar.random": "Случайный вариант", "avatar.save": "Сохранить аватар",
  "contacts.title": "Контактная книга", "contacts.empty": "Клиентов пока нет", "contacts.choose": "Выберите клиента слева",
  "contacts.fullName": "Полное имя", "contacts.organization": "Название организации", "contacts.unp": "УНП",
  "contacts.phone": "Телефон", "contacts.telegram": "Телеграм", "contacts.email": "Почта", "contacts.website": "Сайт",
  "contacts.avatar.change": "Изменить изображение", "contacts.avatar.upload": "Загрузить лого",
  "contacts.avatar.generate": "Создать аватар", "contacts.avatar.failed": "Не удалось сохранить изображение",
  "contacts.edit": "Редактировать контакт", "contacts.new": "Новый контакт", "contacts.name": "Клиент", "contacts.name.required": "Введите имя",
  "theme.toDark": "Включить тёмную тему", "theme.toLight": "Включить светлую тему",
  "auth.email.invalid": "Введите корректный email", "auth.password.tooShort": "Минимум 8 символов", "auth.name.required": "Введите имя", "auth.inviteCode.required": "Введите код приглашения",
} as const;

export type MessageKey = keyof typeof ru;

export function t(key: MessageKey): string {
  return ru[key];
}
